# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "About Us"
  url = "us"
  identifier = "about-us"
  weight = 15

[[main]]
  name = "History"
  url = "us/history/"
  parent = "about-us"
  weight = 20

[[main]]
  name = "Team"
  url = "us/team"
  parent = "about-us"
  weight = 25

[[main]]
  name = "Projects"
  url = "project"
  weight = 30

[[main]]
  name = "News"
  identifier = "blog-news"
  url = ""
  weight = 40

[[main]]
  name = "Blog"
  url = "post"
  parent = "blog-news"
  weight = 30

[[main]]
  name = "Events"
  url = "event"
  parent = "blog-news"
  weight = 40

[[main]]
  name = "Contact"
  url = "contact"
  weight = 50
