# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "About Us"
  url = "us"
  identifier = "about-us"
  weight = 15

[[main]]
  name = "History"
  url = "us/history"
  parent = "about-us"
  weight = 20

[[main]]
  name = "Team"
  url = "us/team"
  parent = "about-us"
  weight = 25

[[main]]
  name = "Projects"
  identifier = "projects"
  url = "project"
  weight = 30

[[main]]
  name = "2018 Quechua Experience"
  parent = "projects"
  url = "project/QuechuaExperience"
  weight = 31

[[main]]
  name = "2019 KIPU"
  parent = "projects"
  url = "project/KIPU"
  weight = 32

[[main]]
  name = "2020 QUIPU"
  parent = "projects"
  url = "project/QUIPU"
  weight = 33

[[main]]
  name = "2021 Quechua Wikipidiya"
  parent = "projects"
  url = "project/QuechuaWikipedia"
  weight = 34

[[main]]
  name = "2022 Warmikunarayku"
  parent = "projects"
  url = "project/Warmikunarayku"
  weight = 35

[[main]]
  name = "News"
  identifier = "blog-news"
  url = ""
  weight = 40

[[main]]
  name = "Blog"
  url = "post"
  parent = "blog-news"
  weight = 30

[[main]]
  name = "Events"
  url = "talk"
  parent = "blog-news"
  weight = 40

[[main]]
  name = "Contact"
  url = "contact"
  weight = 50
